// Preload primary UI font as early as possible (hashed URL from Vite)
import geistSans400 from '@fontsource/geist-sans/files/geist-sans-latin-400-normal.woff2?url'
{
  const link = document.createElement('link')
  link.rel = 'preload'
  link.as = 'font'
  link.type = 'font/woff2'
  link.crossOrigin = 'anonymous'
  link.href = geistSans400
  document.head.appendChild(link)
}

import './assets/tailwind.css'
// Page-level CSS variables (:root / html.dark) used by About / Experience / mixins.
import './styles/_variables.scss'

import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { addCollection } from '@iconify/vue'
import lucideIcons from '@/assets/icons/lucide-subset.json'
import simpleIconsIcons from '@/assets/icons/simple-icons-subset.json'

import App from './App.vue'
import router from './router'

// Register iconify data locally — eliminates remote API calls entirely.
// addCollection reuses the same registry instance, so registering twice is safe.
// Subsets are generated by scripts/build-icon-subset.mjs from the full
// @iconify-json/{lucide,simple-icons} packages, keeping bundle size minimal.
addCollection(lucideIcons as Parameters<typeof addCollection>[0])
addCollection(simpleIconsIcons as Parameters<typeof addCollection>[0])

const app = createApp(App)

app.use(createPinia())
app.use(router)

app.mount('#app')
