import './assets/tailwind.css'

import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { addCollection } from '@iconify/vue'
import lucideIcons from '@/assets/icons/lucide-subset.json'
import simpleIconsIcons from '@/assets/icons/simple-icons-subset.json'

import App from './App.vue'
import router from './router'

// Register iconify data locally — eliminates remote API calls entirely.
// addCollection reuses the same registry instance, so registering twice is safe.
// Subsets are generated by scripts/build-icon-subset.mjs from the full
// @iconify-json/{lucide,simple-icons} packages, keeping bundle size minimal.
addCollection(lucideIcons as Parameters<typeof addCollection>[0])
addCollection(simpleIconsIcons as Parameters<typeof addCollection>[0])

const app = createApp(App)

app.use(createPinia())
app.use(router)

app.mount('#app')
